# http://docs.travis-ci.com/user/languages/go/
language: go

go: 1.6

os:
  - linux
  - osx

env:
  global:
    - GIT_LFS_TEST_DIR="$HOME/git-lfs-tests"
    - GIT_SOURCE_REPO="https://github.com/larsxschneider/git.git"
    - GIT_SOURCE_BRANCH="8a3cb929f7e541aa62f761d92626f7ec27870c55"

before_install:
  - >
    git clone $GIT_SOURCE_REPO git-source;
    cd git-source;
    git checkout $GIT_SOURCE_BRANCH;
    case "${TRAVIS_OS_NAME:-linux}" in
    linux)
      make --jobs=2
      ;;
    osx)
      brew install gettext
      brew link --force gettext
      NO_OPENSSL=YesPlease APPLE_COMMON_CRYPTO=YesPlease make --jobs=2
      ;;
    esac;
    make install;
    export PATH=$PWD:$PATH;
    cd ..;
    repo=`basename $PWD`;
    localDir=`dirname $PWD`;
    cfDir="`dirname $localDir`/github";
    if [[ "$localDir" != "$cfDir" ]];
    then
      mv "$localDir" "$cfDir";
      cd ../../github/$repo;
      export TRAVIS_BUILD_DIR=`dirname $TRAVIS_BUILD_DIR`/$repo;
    fi;

install: true

script: script/cibuild

notifications:
  email: false
